<h2>Module Metrics</h2>
<div class="result-table">
    <ul class="list-group">
        <li class="list-group-item col-md-12">Filename</li>

        <li class="list-group-item col-md-2">Type</li>
        <li class="list-group-item col-md-2">First Line of Code</li>
        <li class="list-group-item col-md-2">Last Line of Code</li>
        <li class="list-group-item col-md-2">Packagename</li>
        <li class="list-group-item col-md-2">Classname</li>
        <li class="list-group-item col-md-2">Methodname</li>

        <li class="list-group-item col-md-12">Detailed Message</li>
    </ul>
    <?php foreach ( $data->aViolations as $oViolation ) { ?>
        <ul class="list-group">
            <li class="list-group-item col-md-12"><?php echo $oViolation->getFile(); ?></li>

            <li class="list-group-item col-md-2"><?php echo $oViolation->getType(); ?></li>
            <li class="list-group-item col-md-2"><?php echo $oViolation->getInformation( 'Begin' ); ?></li>
            <li class="list-group-item col-md-2"><?php echo $oViolation->getInformation( 'End' ); ?></li>
            <li class="list-group-item col-md-2"><?php echo $oViolation->getInformation( 'Package' ); ?></li>
            <li class="list-group-item col-md-2"><?php echo $oViolation->getInformation( 'Class' ); ?></li>
            <li class="list-group-item col-md-2"><?php echo $oViolation->getInformation( 'Method' ); ?></li>

            <li class="list-group-item col-md-12"><?php echo $oViolation->getMessage(); ?></li>
        </ul>
    <?php } ?>
</div>
