<div class="page-header">
    <h2>Certification Price</h2>
</div>

<div class="alert alert-info">Please note that the listed price is only an estimate. The actual price depends on the
manual investigation of your module and might differ significantly.</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Metrics</h3>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Remark</th>
            <th class="text-right">Value</th>
            <th class="text-right">Factor</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Code Coverage</td>
            <td>Has to be > 90%. Values below result in manual work when testing.</td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('Code Coverage')->getValue() ?>%</td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('Code Coverage')->getFactor() ?></td>
        </tr>
        <tr>
            <td>C.R.A.P Index</td>
            <td>The Change Risk Analysis and Predictions (CRAP) index of a function or method uses cyclomatic complexity and code coverage from automated tests to help estimate the effort and risk associated with maintaining legacy code. A CRAP index over 30 is a good indicator of crappy code.</td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('C.R.A.P Index')->getValue() ?></td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('C.R.A.P Index')->getFactor() ?></td>
        </tr>
        <tr>
            <td>NPath Complexity</td>
            <td>The NPATH metric computes the number of possible execution paths through a function. It takes into account the nesting of conditional statements and multi-part boolean expressions (e.g., A && B, C || D, etc.).
                A NPATH Complexity over 200 is a good candidate for a closer decomposition.</td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('NPath Complexity')->getValue() ?></td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('NPath Complexity')->getFactor() ?></td>
        </tr>
        <tr>
            <td>Cyclomatic Complexity</td>
            <td>Checks cyclomatic complexity against a specified limit. The complexity is measured by the number of if, while, do, for, ?:, catch, switch, case  statements, and operators && and || (plus one) in the body of a constructor, method, static initializer, or instance initializer. It is a measure of the minimum number of possible paths through the source and therefore the number of required tests. Generally 1-4 is considered good, 5-7 ok, 8-10 consider re-factoring, and 11+ re-factor now!</td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('Cyclomatic Complexity')->getValue() ?></td>
            <td class="text-right"><?php echo $data->certificationResult->getCertificationRule('Cyclomatic Complexity')->getFactor() ?></td>
        </tr>
        <tr>
            <td colspan="3"><b>Total Factor</b></td>
            <td class="text-right"><b><?php echo $data->certificationResult->getFactor() ?></b></td>
        </tr>
        </tbody>
    </table>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Price</h3>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Type</th>
            <th>Remark</th>
            <th class="text-right">Value</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Basic factor price</td>
            <td>The basic factor price is multiplied by the determined software quality factor.</td>
            <td class="text-right">119,00&euro;</td>
        </tr>
        <tr>
            <td>Total factor price</td>
            <td>Multiply basic factor price by the total factor price</td>
            <td class="text-right"><?php echo number_format($data->certificationResult->getFactor() * 200, 2, ',', '.') ?>&euro;</td>
        </tr>
        <!--        <tr>-->
        <!--            <td>Basic price software quality</td>-->
        <!--            <td>Per certification attempt (or check for attempt or pre-check). 1 feedback cycle included.</td>-->
        <!--            <td>250€</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>Certification flat charge</td>-->
        <!--            <td>This covers technical code reviewing and module testing based on OXID eSales module certification rules (OXID_Module_Certification_Rules.pdf)</td>-->
        <!--            <td>960&euro;</td>-->
        <!--        </tr>-->
        <tr>
            <td colspan="2"><b>Total Certification Price</b></td>
            <td class="text-right"><b><?php echo number_format($data->certificationResult->getPrice(), 2, ',', '.') ?>&euro;</b></td>
        </tr>
        </tbody>
    </table>
</div>