<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $data->sHeading; ?></h3>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Class</th>
            <th>Method</th>
            <th>Line</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ( $data->violations as $violation ) { ?>
            <tr>
                <td><?php echo $violation->getClass() ?></td>
                <td><?php echo $violation->getMethod() ?></td>
                <td><?php echo $violation->getBeginLine() ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>