<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="../../resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="../../resource/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="../../resource/css/custom.css">
        <script src="../../resource/js/jquery.min.js"></script>
        <script src="../../resource/js/bootstrap.min.js"></script>
        <!--[if lt IE 9]>
        <script src="../../resource/js/html5shiv.js"></script>
        <script src="../../resource/js/respond.min.js"></script>
        <![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>OXID Module Certification Result</title>
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1>OXID eShop Module Certification Metrics</h1>
            </div>
            <?php echo $data->sCertificationResult ?>

            <div class="page-header">
                <h2>Violations</h2>
            </div>
<!--            --><?php //foreach ( $data->aCertViolations as $aCertViolation ) { ?>
<!--                --><?php //echo $aCertViolation; ?>
<!--            --><?php //} ?>
            <?php foreach ( $data->aFileViolations as $aFileViolation ) { ?>
                <?php echo $aFileViolation; ?>
            <?php } ?>

            <div class="page-header">
                <h2>Generic Checks</h2>
            </div>
            <?php foreach ( $data->aGenericChecks as $aGenericCheck ) { ?>
                <?php echo $aGenericCheck; ?>
            <?php } ?>
        </div>
    </body>
</html>
