<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="../../resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="../../resource/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="../../resource/css/custom.css">
        <script src="../../resource/js/jquery.min.js"></script>
        <script src="../../resource/js/bootstrap.min.js"></script>
        <!--[if lt IE 9]>
        <script src="../../resource/js/html5shiv.js"></script>
        <script src="../../resource/js/respond.min.js"></script>
        <![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>OXID Module Certification Result</title>
    </head>
    <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">OXID Module Certification Tool</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#price">Pricing</a></li>
                    <li><a href="#violations">Violations</a></li>
                    <li><a href="#checks">Generic Checks</a></li>
                </ul>
            </div>
        </div>
    </nav>
        <div class="container">

            <div id="price">
                <?php echo $data->sCertificationResult ?>
            </div>

            <div id="violations">
                <div class="page-header">
                    <h2>Violations</h2>
                </div>
    <!--            --><?php //foreach ( $data->aCertViolations as $aCertViolation ) { ?>
    <!--                --><?php //echo $aCertViolation; ?>
    <!--            --><?php //} ?>
                <?php foreach ( $data->aFileViolations as $aFileViolation ) { ?>
                    <?php echo $aFileViolation; ?>
                <?php } ?>
            </div>

            <div id="checks">
                <div class="page-header">
                    <h2>Generic Checks</h2>
                </div>
                <?php foreach ( $data->aGenericChecks as $aGenericCheck ) { ?>
                    <?php echo $aGenericCheck; ?>
                <?php } ?>
            </div>
        </div>
    </body>
</html>
