<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="../../resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="../../resource/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="../../resource/css/custom.css">
        <script src="../../resource/js/jquery.min.js"></script>
        <script src="../../resource/js/bootstrap.min.js"></script>
        <!--[if lt IE 9]>
        <script src="../../resource/js/html5shiv.js"></script>
        <script src="../../resource/js/respond.min.js"></script>
        <![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>OXID Module Certification Result</title>
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1>OXID eShop Module Certification Metrics</h1>
            </div>
            <?php foreach ( $data->oModules as $sModule ) { ?>
                <?php echo $sModule; ?>
            <?php } ?>
        </div>
    </body>
</html>
